name: ovesdu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Search Flatter in Dart Packages - Global constants - CUSTOM
  # Used to store local state
  hive:
  # Search path_provider in Dart Packages - CUSTOM
  path_provider:
  # Search provider in Dart Packages - CUSTOM
  # Used to manage global app state
  provider:
  # Облегчает использование SVG - векторной графики
  flutter_svg:
  # Локализация - подключение языкового пакета
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Custom
  #     fonts:
  #       - asset: assets/fonts/28DaysLaterCyr.ttf
  #         style: italic
        # - asset: assets/fonts/DSBrushes.ttf
        # - asset: assets/fonts/PaperCuts2.ttf
        # - asset: assets/fonts/SlimamifMedium.ttf
        # - asset: assets/fonts/Staccato555TLReqular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
